In [8]:
# numpy whithout loop
import numpy as np
a = np.arange(5)
a * a


array([ 0,  1,  4,  9, 16])

In [9]:
# pyton messay loop
import numpy as np
a = np.arange(5)
a * a


array([ 0,  1,  4,  9, 16])

In [10]:
# exponent and logarithm
import numpy as np
np.exp([1,2,3])
np.log([1,10,100])
np.sqrt([1,4,9])

array([1., 2., 3.])

In [11]:
#Summing the values in an array
import numpy as np
rng = np.random.default_rng()
L = rng.random(100)
sum(L)

np.float64(51.52448403509562)

In [12]:
# Multidimensional aggregation
import numpy as np
m= np.array([[1,2,3],[4,5,6]])
row_sum =np.sum(m, axis=1)
print(row_sum)
col_sum=np.sum(m,axis=0)
print(col_sum)
m.sum()

[ 6 15]
[5 7 9]


np.int64(21)

In [13]:
import numpy as np
m=rng .integers(0,10,(3,4))
print(m)
np.nansum(m)

[[5 5 4 1]
 [2 0 6 8]
 [2 0 1 9]]


np.int64(43)

In [14]:
#nan handling (Because NaN means unknown. Add unknown to anything → result is unknown).
import numpy as np
a = np.array([10, 20, np.nan, 40])
np.nansum(a)
 #np.sum()    --> Result=nan


np.float64(70.0)

In [ ]:
# Create a NumPy array of numbers 1–20
#Reshape it into (4, 5)
#Find:
       #Mean of each row
       #Max of each column
import numpy as np
a= np.arange(1,21);
print(a)
b=a.reshape(4,5)
print(b)
c = b.mean(axis=1) #Row axis=1
print("Mean of each row:", c)

d = b.max(axis=0) # Column axis=0
print("Max of each column:", d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Mean of each row: [ 3.  8. 13. 18.]
Max of each column: [16 17 18 19 20]


In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

total_sum = arr.sum()
n = arr.size

result = (total_sum - arr) / (n - 1)

print(result)


[3.5  3.25 3.   2.75 2.5 ]


In [4]:
#Square of the numbers
import numpy as np

a= np.arange(1,7)
sq=a**2
print(sq)

[ 1  4  9 16 25 36]


In [5]:
#Normalize the array
import numpy as np
a= np.array([10,20,30,40,50])
norm=(a-np.min(a))/(np.max(a)-np.min(a))
print(norm)

[0.   0.25 0.5  0.75 1.  ]


In [7]:
#Z-score Standardization
import numpy as np
a=np.array([10,20,30,40,50])
b=np.mean(a)
c=np.std(a)
z_score= (a-b)/c
print(z_score)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
